# Generated by Django 6.0.2 on 2026-02-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0005_remove_course_exam_date_remove_course_resources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm'), ('ENDTERM', 'Endterm'), ('CA', 'Continuous Assessment')], max_length=20)),
                ('date', models.DateTimeField()),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='exams/syllabi/')),
                ('resources', models.FileField(blank=True, null=True, upload_to='exams/resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='attendance.course')),
            ],
        ),
    ]
