# Generated by Django 6.0.2 on 2026-02-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('CA', 'Continuous Assessment (CA)'), ('MID', 'Mid Term Examination'), ('END', 'End Term Examination')], max_length=20),
        ),
    ]
