# Generated by Django 6.0.2 on 2026-03-02 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_exam_type'),
        ('resource_management', '0002_campusresource_classroom_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='resource_management.classroom'),
        ),
    ]
