# Generated by Django 6.0.2 on 2026-02-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('WORKING', 'Operational'), ('MAINTENANCE', 'In Maintenance'), ('BROKEN', 'Out of Order')], default='WORKING', max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('SEMINAR_HALL', 'Seminar Hall'), ('OFFICE', 'Faculty Office')], default='CLASSROOM', max_length=20),
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_on', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resource_management.classroom')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='resource_management.campusresource')),
            ],
        ),
    ]
