# Generated by Django 6.0.2 on 2026-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedial_classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedialsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
