# Generated by Django 6.0.2 on 2026-02-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_courseresource_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
        migrations.DeleteModel(
            name='CourseResource',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
