# Generated by Django 6.0.2 on 2026-02-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_exam_course_course_exam_date_course_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
    ]
