# Generated by Django 6.0.2 on 2026-02-23 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_course_exam_date_remove_course_resources_and_more'),
        ('core', '0003_section_user_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('slot_number', models.IntegerField(help_text='Slot 1-7 (e.g. 9AM to 4PM)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='attendance.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='core.section')),
            ],
            options={
                'unique_together': {('day_of_week', 'slot_number', 'section')},
            },
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.timetableslot'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('date', 'slot')},
        ),
    ]
