# Generated by Django 6.0.2 on 2026-02-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancesession_date_timetableslot_and_more'),
        ('remedial_classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='remedial_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remedial_classes.remedialsession'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('date', 'slot', 'remedial_session')},
        ),
    ]
