# Generated by Django 6.0.2 on 2026-02-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancesession_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together=set(),
        ),
    ]
