# Generated by Django 6.0.2 on 2026-02-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_timetableslot_unique_together'),
        ('resource_management', '0002_campusresource_classroom_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='resource_management.classroom'),
        ),
    ]
